import re
from typing import Any, Iterable


def parse_almost_json(file_name: str) -> Iterable[Any]:
    """Parse the "almost-json" that was generated by the Rust code.

    Args:
        file_name (str): the file name to parse

    Returns:
        Iterable[Any]: the contents of the file parsed
                       into a series of JSON objects
    """
    json_name = file_name.replace("_raw.txt", ".json")
    with open(file_name) as f, open(json_name, 'w') as outfile:
        #TODO doesn't work
        text = f.read()
        parse_json = re.sub('}{', '},\n{', text)
        outfile.seek(0)
        outfile.write('[' + parse_json + '\n]')
        outfile.truncate()


if __name__ == "__main__":
    parse_almost_json("game_info_raw.txt")
    parse_almost_json("games_raw.txt")
