import json
from typing import Any, Iterable


def parse_almost_json(file_name: str) -> Iterable[Any]:
    """Parse the "almost-json" that was generated by the Rust code.

    Args:
        file_name (str): the file name to parse

    Returns:
        Iterable[Any]: the contents of the file parsed
                       into a series of JSON objects
    """
    with open(file_name) as f:
        # TODO doesn't work
        print(json.load(f))


if __name__ == "__main__":
    parse_almost_json("game_info_raw.txt")
